### ISSUE TITLE
toa_format will return "Comment" if file name begins with "C"

### ISSUE THREAD

**Issue by pennucci** [demorest/tempo_utils#8]
I recommend changing:
    if line[0]=='C'
to:
    if line[:2]=='C '
otherwise files (like those that start with "CHIME_") will not be flagged as TOAs, but rather comments.

**Comment by demorest** [comment]
Hm, I thought I had done that years ago.  Maybe it never made it to github.  Just changed it to `line.startswith('C ')`.  I vaguely remember some possible issues with old-style TOAs but this is probably better for most modern usage.
